name: QA

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        cd 03-ocr
        npm install
    - name: Run code analysis
      run: |
        cd 03-ocr
        npm run analyse
    - name: Run tests
      run: |
        cd 03-ocr
        npm run test
    - name: Creating release
      run: |
        echo Creating release ...
        echo Created release :-)
